name: CI-CD-With-n8n

on:
  push:
    branches:
      - main      
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "üèóÔ∏è Building application..."
          sleep 2

      - name: Test
        run: |
          echo "üß™ Running tests..."
          sleep 2

      - name: Deploy
        run: |
          echo "üöÄ Deploying to production..."
          sleep 2

      - name: Notify n8n (Success)
        if: success()
        run: |
          curl -X  POST "http://ec2-34-231-244-17.compute-1.amazonaws.com:5678/webhook-test/b4bedb3f-8035-4231-b70c-f5f6d531e7f5" \
          -H "Content-Type: application/json" \
          -d '{
            "status": "success",
            "repo": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}",
            "env": "production"
          }'

      - name: Notify n8n (Failure)
        if: failure()
        run: |
          curl -X  POST "http://ec2-34-231-244-17.compute-1.amazonaws.com:5678/webhook-test/b4bedb3f-8035-4231-b70c-f5f6d531e7f5" \
          -H "Content-Type: application/json" \
          -d '{
            "status": "failure",
            "repo": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}",
            "env": "production"
          }'
      - name: Notify n8n
        if: always()
        run: |
          STATUS=${{ job.status }}
          curl -X POST "${{ secrets.N8N_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d "{\"status\":\"$STATUS\",\"repo\":\"${{ github.repository }}\",\"commit\":\"${{ github.sha }}\",\"actor\":\"${{ github.actor }}\",\"env\":\"production\"}"
